name: C/C++ CI

on:
  push:
    branches:
      - branchHTTPserver
  pull_request:
    branches:
      - branchHTTPserver

jobs:
  build:
    name: Build and Push Multi-Arch Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Review code
        uses: actions/checkout@v4

      - name: Downloading QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure

      - name: Sign in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ variable.login }}
          password: ${{ secrets.password }}

      - name: Create and push a Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./source
          file: ./source/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kleshchenkoyurii686/optimaserver:latest
