name: C/C++ CI

on:
  push:
    branches: [ "branchAutoTest" ]
  pull_request:
    branches: [ "branchAutoTest" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
    - name: Install build dependencies
      run: sudo apt-get install -y autoconf automake libtool
    - name: Run autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure   
    - name: make
      run: make
    - name: Test
      run: cd ./tests && make check
